### ISSUE TITLE
No Rename and Delete action menu in Content Bank (Moodle 3.9)

### ISSUE THREAD

**Issue by Aldises** [moodleuulm/moodle-theme_boost_campus#91]
Hi, 

Just to let you know, there is no option to rename or delete an H5P content in the Content Bank in Moodle 3.9 

![image](https://user-images.githubusercontent.com/10154178/88368655-cd33de00-cd8e-11ea-81b3-fa03e7343057.png)

Do you have any idea when your theme will be 3.9 compatible ?

All the best

**Comment by christianwolters** [comment]
Hi,

I can confirm this issue, to reproduce:

- open the content bank, e.g. from the h5pactivity form, /contentbank/index.php?contextid=[yourcontext]
- open a content by clicking on the linked name in Content name coloumn
- on the next page you have _1_ cog symbol in the upper right corner

In boost_campus this is cog-icon gives access to a action menu with the **course actions**:

![grafik](https://user-images.githubusercontent.com/2005580/88786858-55e9ba00-d193-11ea-9cce-6a34b1650dc7.png)

The screenshot above posted by @Aldises shows the action menu in boost with **content bank actions**.
In boost there is only this action menu, no cog with course-related links.

Best regards
Christian

**Comment by Kathrin84** [comment]
Hello all,

I've fixed this bug with this commit: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/70cefa1a65146e7d5c34dc33e17e8a3dccc8bd10

However, this is just an interim solution and we hope that Moodle core will improve the placement of this cog icon. I've opened a tracker issue for this:
https://tracker.moodle.org/browse/MDL-69793

I will keep this issue open for some more time.

Best, Kathrin

**Comment by abias** [comment]
As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. 

Against this background, I am afraid that this interim solution will remain as it is until Boost Campus will reach end of life.

**Comment by abias** [comment]
This plugin has finally reached end of life.
Against this background, I will close this issue.
